# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "/improving-america/" # the subpath of your site, e.g. /blog/
url: "http://unsolvedcypher.github.io/improving-america" # the base hostname & protocol for your site 

# User settings
username: Improving America
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: A commonsense platform to help solve America's problems
email: americanimprovement@matthewmcmillan.me
twitter_username: UnsolvedCypher
github_username:  UnsolvedCypher
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
